apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 80          # Service port
      targetPort: 5000  # Container port (should match your Flask app)
      nodePort: 30001   # Node port
